### ISSUE TITLE
How to run this application?

### ISSUE THREAD

**Issue by phoenixg** [gomeplusFED/AMP#3]

**Comment by luoye-fe** [comment]
这个项目暂时内部使用，代码梳理和文档整理还在进行中，接下来会有开源计划。

如果想要运行的话，用 dev 分支下的代码。
- 安装 `mongodb 3.0/node/webpack`
- 新建名为 `AMP` 的数据库
- 安装项目依赖
- 修改 `config` 目录下的相关配置文件。基础配置：端口、ldap等；数据库配置：开发数据库，生产环境数据库；
-  执行 `node app.babel.js --env=pro` 以开发方式启动程序（后台程序，连接开发数据库）。 
- 执行 `npm run dev` 编译前端静态文件（开发模式，实时编译）。
- 打开浏览器，默认http 9090 端口，https 8989 端口，查看详情

感谢对本项目的关注。

**Comment by phoenixg** [comment]
安装 mongodb 3.0/node/webpack, 可否具体说说怎么装？
新建名为 AMP 的数据库， 这是mongodb的数据库， 要怎么新建？
安装项目依赖，这个要怎么安装？

可以详解一步步步骤吗？谢谢！

**Comment by luoye-fe** [comment]
谷歌吧~这个要写的明明白白够呛。
项目依赖 npm 安装

**Comment by phoenixg** [comment]
弄得简单点吧， 我还是没弄出来

**Comment by luoye-fe** [comment]
会的，不久就会开源，会把文档补齐。

现在遇到什么问题了？mongodb么？

**Comment by luoye-fe** [comment]
@phoenixg  文档已经补齐，可根据 master 下文档部署。如果没有问题，关 issue 了。

[部署文档](https://github.com/gomeplusFED/AMP/blob/master/doc/deploy.md)

**Comment by phoenixg** [comment]
好的， 已经部署起来，谢谢！
不嫌麻烦的话， 我会提些需求～

**Comment by luoye-fe** [comment]
哈，可以，但是只能空余时间来做，不一定跟得上。

可以提PR呀

**Comment by phoenixg** [comment]
宝宝不会nodejs～～～

**Comment by luoye-fe** [comment]
＝ ＝好吧
