### ISSUE TITLE
注册过程中报错2

### ISSUE THREAD

**Issue by heroWang** [gomeplusFED/AMP#5]
我注册完跳转到主页面以后,报错.
Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
server error { [MongoError: not master and slaveOk=false]
  name: 'MongoError',
  message: 'not master and slaveOk=false',
  ok: 0,
  errmsg: 'not master and slaveOk=false',
  code: 13435 } { request:
   { method: 'GET',
     url: '/api/projects?limit=15&page=1',
     header:
      { host: '121.40.194.97:9090',
        connection: 'keep-alive',
        accept: 'application/json, text/plain, _/_',
        'x-requested-with': 'XMLHttpRequest',
        'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36',
        referer: 'http://121.40.194.97:9090/',
        'accept-encoding': 'gzip, deflate, sdch',
        'accept-language': 'zh-CN,zh;q=0.8,en;q=0.6',
        cookie: 'ldap=; koa:sid=eyJpc0xvZ2luIjp0cnVlLCJ1c2VyaW5mbyI6IiJ9' } },
  response:
   { status: 404,
     message: 'Not Found',
     header:
      { 'access-control-allow-origin': '*',
        'access-control-allow-methods': 'GET,HEAD,PUT,POST,DELETE' } },
  app: { subdomainOffset: 2, proxy: false, env: 'development' },
  originalUrl: '/api/projects?limit=15&page=1',
  req: '<original node req>',
  res: '<original node res>',
  socket: '<original node socket>' }

是要求必须要连mongos吗? 我连的是mongod,没有建集群,这样可以吗?

另外,代码里好多空指针错误.我都给修了.代码跑不起来啊.
是我环境有问题,还是你们代码没有测试的原因呢?

**Comment by luoye-fe** [comment]
node怎么会报空指针错误＝ ＝，mongodb 有新建名为AMP的数据库么？

**Comment by heroWang** [comment]
哦,我的意思是没有判断空值造成的错误.已经建了AMP了.@luoye-fe

**Comment by heroWang** [comment]
这是我的配置.
base.config.js
export default {
        httpPort: 9090,
        httpsPort: 8989,
        ldap:{
        use:false
        }
};

db.config.js
export default {
        dev: {
                host: 'localhost',
                port: '7210',
                username: '',
                password: '',
                database: 'AMP-dev'
        },
        production: {
                host: 'localhost',
                port: '7210',
                username: '',
                password: '',
                database: 'AMP'
        }
};

**Comment by luoye-fe** [comment]
mongodb 只能用3.0 版本，mongose 我这是 4.4.16 。

这是mongodb报的错，如果排除版本问题的话，应该是数据库本身的设置问题。

[看这个能否解决问题](http://stackoverflow.com/questions/8990158/mongodb-replicates-and-error-err-not-master-and-slaveok-false-code)

**Comment by heroWang** [comment]
不行,我的是单独一个mongod实例.没有副本集.

**Comment by luoye-fe** [comment]
在命令行中进行一些数据的增删改查操作，看是否有具体的错误信息，根据错误信息可以定位问题在哪，然后再看怎么做。

如果还是报 `not master and slaveOk=false', code: 13435` 应该是 SECONDARY 的问题。

**Comment by luoye-fe** [comment]
你是做了主从么？连的是从的话需要在主上设置  `slaveok=ok` 让从可读写

**Comment by heroWang** [comment]
问题解决了,我的mongo有问题.配置文件里有 replSet属性.删掉重启就可以用了.
感谢 你的耐心解答.@luoye-fe

**Comment by luoye-fe** [comment]
ok，解决就好。

感谢关注 AMP
