### ISSUE TITLE
API列表查询error

### ISSUE THREAD

**Issue by anlia260** [gomeplusFED/AMP#9]
![error](https://cloud.githubusercontent.com/assets/11311553/20054840/8dba47ce-a519-11e6-9357-637fd827fb50.jpg)

**Comment by luoye-fe** [comment]
给详细一点的错误信息吧，看起来应该是接口给的数据出错了。

**Comment by anlia260** [comment]
第一次查询是OK的，但是当我第二次查询的时候会报this指针没有apis的属性。

**Comment by luoye-fe** [comment]
额。。。具体的报错信息呢？
看起来是你的项目ID不对，从 mock 跟路径那个地方看你的项目ID是空，然后后台去查询的时候没有具体信息，接口数据不对，前端处理报错了。

**Comment by anlia260** [comment]
![image](https://cloud.githubusercontent.com/assets/11311553/21090101/5e37c7f4-c078-11e6-932c-d13a6a56e49e.png)
![image](https://cloud.githubusercontent.com/assets/11311553/21090127/7e012328-c078-11e6-8038-a2fc8175bee2.png)
@luoye-fe，帮我看下，为什么是500？

**Comment by luoye-fe** [comment]
应该是你的api信息填写不对，只支持json格式的返回示例

**Comment by anlia260** [comment]
是的，我只是填写返回参数，并没有给返回示例。问下，返回参数有什么用吗？

**Comment by luoye-fe** [comment]
返回参数是对返回示例里涉及到的字段的解释

**Comment by luoye-fe** [comment]
返回示例必填，空的话给个 {}

**Comment by anlia260** [comment]
谢谢 @luoye-fe

**Comment by anlia260** [comment]
![image](https://cloud.githubusercontent.com/assets/11311553/21134299/1db3fca8-c158-11e6-8793-15d0cf70dfcb.png)
![image](https://cloud.githubusercontent.com/assets/11311553/21134306/2bfdf304-c158-11e6-8cb5-63446fda3d79.png)
报500了会是什么原因呢？

**Comment by luoye-fe** [comment]
后台报了什么错？

**Comment by anlia260** [comment]
![image](https://cloud.githubusercontent.com/assets/11311553/21166318/bf8f3b78-c1df-11e6-85ee-c79f31ec9bb0.png)
这是Pm2的日志

**Comment by anlia260** [comment]
可以要你一个IM吗？一直在issues请教这种问题总感觉不好^_^

**Comment by luoye-fe** [comment]
url 里的 query 中 id 字段你写的是空，后台没有做这样的处理 = = 

`XXXX?id=&page=1`

`id`

IM 的话我另一个[项目](https://github.com/luoye-fe/goh5)里有 ~

**Comment by anlia260** [comment]
我是说你的 即时通讯方式^_^

**Comment by luoye-fe** [comment]
拉到最后。。微信截图。。
